#!/usr/bin/env python3
"""Convert validated SPIR-V binaries into a deterministic C++ header."""

from __future__ import annotations

import argparse
import struct
from pathlib import Path


def read_words(path: Path) -> tuple[int, ...]:
    data = path.read_bytes()
    if not data or len(data) % 4 != 0:
        raise ValueError(f"SPIR-V input must contain a non-empty whole number of words: {path}")
    return struct.unpack(f"<{len(data) // 4}I", data)


def format_array(name: str, words: tuple[int, ...]) -> str:
    lines = [f"inline constexpr std::array<std::uint32_t, {len(words)}> {name}{{{{"]
    for begin in range(0, len(words), 8):
        chunk = ", ".join(f"0x{word:08x}U" for word in words[begin : begin + 8])
        lines.append(f"    {chunk},")
    lines.append("}};")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Embed vertex and fragment SPIR-V in a C++ header")
    parser.add_argument("--vertex", type=Path, required=True)
    parser.add_argument("--fragment", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()

    vertex = read_words(arguments.vertex)
    fragment = read_words(arguments.fragment)
    text = "\n".join(
        (
            "#pragma once",
            "",
            "// Generated by tools/embed_spirv.py. Do not edit.",
            "#include <array>",
            "#include <cstdint>",
            "",
            "namespace ai2d::embedded_shaders {",
            "",
            format_array("sprite_vertex_spirv", vertex),
            "",
            format_array("sprite_fragment_spirv", fragment),
            "",
            "} // namespace ai2d::embedded_shaders",
            "",
        )
    )
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    if not arguments.output.is_file() or arguments.output.read_text(encoding="utf-8") != text:
        arguments.output.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
