include_guard(GLOBAL)

function(ai2d_enable_sanitizers target)
    if(AI2D_ENABLE_ASAN)
        if(MSVC)
            target_compile_options(${target} INTERFACE /fsanitize=address /Zi)
            target_link_options(${target} INTERFACE /INCREMENTAL:NO /DEBUG)
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            target_compile_options(${target} INTERFACE -fsanitize=address -fno-omit-frame-pointer)
            target_link_options(${target} INTERFACE -fsanitize=address)
        else()
            message(FATAL_ERROR "AI2D_ENABLE_ASAN is unsupported by ${CMAKE_CXX_COMPILER_ID}")
        endif()
    endif()

    if(AI2D_ENABLE_UBSAN)
        if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            target_compile_options(${target} INTERFACE -fsanitize=undefined -fno-omit-frame-pointer)
            target_link_options(${target} INTERFACE -fsanitize=undefined)
        else()
            message(FATAL_ERROR "AI2D_ENABLE_UBSAN is unavailable for this compiler")
        endif()
    endif()
endfunction()
